######################
# SERVERS TRANSPORTS #
######################
http:
  serversTransports:
    insecureTransport:
      insecureSkipVerify: true  # Since homepage uses self-signed cert internally
