---
- name: Update all servers
  hosts: all
  vars:
    ansible_host_key_checking: false ##If you get an error about hosts not trusted
  become: yes
  become_user: root
  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes
      cache_valid_time: 3600  # Time in seconds to consider the cache valid

  - name: Upgrade all packages
    apt:
      upgrade: dist  # You can also use 'safe' or 'full' depending on your needs

  - name: Autoremove unnecessary packages
    apt:
      autoremove: yes

- name: Install Docker and Docker Compose
  hosts: all
  become: yes
  gather_facts: true
  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes
    
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes
